# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'situationSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 89)
        self.btnTas = QtWidgets.QPushButton(Dialog)
        self.btnTas.setGeometry(QtCore.QRect(10, 20, 93, 61))
        self.btnTas.setProperty("SelectedSituation", "")
        self.btnTas.setObjectName("btnTas")
        self.btnKagit = QtWidgets.QPushButton(Dialog)
        self.btnKagit.setGeometry(QtCore.QRect(120, 20, 93, 61))
        self.btnKagit.setObjectName("btnKagit")
        self.btnMakas = QtWidgets.QPushButton(Dialog)
        self.btnMakas.setGeometry(QtCore.QRect(230, 20, 93, 61))
        self.btnMakas.setObjectName("btnMakas")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnTas.setText(_translate("Dialog", "Taş"))
        self.btnKagit.setText(_translate("Dialog", "Kağıt"))
        self.btnMakas.setText(_translate("Dialog", "Makas"))
