# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnoyunabasla = QtWidgets.QPushButton(self.centralwidget)
        self.btnoyunabasla.setGeometry(QtCore.QRect(30, 140, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnoyunabasla.setFont(font)
        self.btnoyunabasla.setObjectName("btnoyunabasla")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 241, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.tursayisi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tursayisi.setFont(font)
        self.tursayisi.setObjectName("tursayisi")
        self.horizontalLayout_2.addWidget(self.tursayisi)
        self.sonuclar = QtWidgets.QLabel(self.centralwidget)
        self.sonuclar.setGeometry(QtCore.QRect(30, 270, 441, 411))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sonuclar.setFont(font)
        self.sonuclar.setFrameShape(QtWidgets.QFrame.Box)
        self.sonuclar.setText("")
        self.sonuclar.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuclar.setObjectName("sonuclar")
        self.btnTas = QtWidgets.QPushButton(self.centralwidget)
        self.btnTas.setGeometry(QtCore.QRect(30, 210, 93, 51))
        self.btnTas.setObjectName("btnTas")
        self.btnKagit = QtWidgets.QPushButton(self.centralwidget)
        self.btnKagit.setGeometry(QtCore.QRect(200, 210, 93, 51))
        self.btnKagit.setObjectName("btnKagit")
        self.btnMakas = QtWidgets.QPushButton(self.centralwidget)
        self.btnMakas.setGeometry(QtCore.QRect(370, 210, 93, 51))
        self.btnMakas.setObjectName("btnMakas")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taş Kağıt Makas"))
        self.label.setText(_translate("MainWindow", "Taş Kağıt Makas"))
        self.btnoyunabasla.setText(_translate("MainWindow", "Oyuna Başla"))
        self.label_3.setText(_translate("MainWindow", "Tur Sayısı :"))
        self.btnTas.setText(_translate("MainWindow", "TAŞ"))
        self.btnKagit.setText(_translate("MainWindow", "KAĞIT"))
        self.btnMakas.setText(_translate("MainWindow", "MAKAS"))
